STYLE_CLASS = handout
include $(STYLE_DIR)/Makefile.rules

doc: README.pdf

web-install:
	cp README.pdf $(WEB_DIR)/stylesheets-readme.pdf 

web-links:
	echo '<li><a href="stylesheets-readme.pdf">Zilogic Stylesheets HOW-TO</a></li>' >> $(WEB_CAT_ART)

